### ISSUE TITLE
configure component to not show 'Now' button

### ISSUE THREAD

**Issue by Esniper90** [talkhabi/vue-persian-datetime-picker#109]
Is there any prop to not show "Now" button inside component?

**Comment by talkhabi** [comment]
Hi @Esniper90, there is no direct config for this but you can hide it by css:
```css
.vpd-actions button:nth-child(3) {
    display: none;
}
```
