### ISSUE TITLE
Action buttons don't inherit font-family

### ISSUE THREAD

**Issue by Wintersunner** [talkhabi/vue-persian-datetime-picker#162]
The buttons in vpd-actions class doesn't inherit font-family from parent.

**Comment by talkhabi** [comment]
I think it depends on the library you use
Just set it globally
```css
button, input, optgroup, select, textarea {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}
```
