### ISSUE TITLE
How to show datepicker as dropdown - not popup

### ISSUE THREAD

**Issue by essivision** [talkhabi/vue-persian-datetime-picker#65]
I wanna to change datepicker style to show as dropdown like this datepicker:
![datepicker](https://user-images.githubusercontent.com/7271330/59565002-f26dfd00-9062-11e9-8199-4339f166269c.jpg)

What should I do?

**Comment by talkhabi** [comment]
Hi @essivision, Sorry there is no direct config for this but you can style it as below
```css
.vpd-wrapper {
    position: relative !important;
    height: 0 !important;
}
.vpd-wrapper .vpd-container {
    transform: none !important;
    top: 0 !important;
    left: 0 !important;
}
```
